---
version: 2.1
jobs:
  build:
    docker:
      - image: debian:9.8

    steps:
      - checkout
      - run: apt update
      - run: apt install -y curl libssl-dev libtinfo-dev
      - run: curl -sSL https://get.haskellstack.org/ | sh

      - restore_cache:
          keys:
            - v1-stack-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
            - v1-stack-{{ checksum "package.yaml" }}-
            - v1-stack-

      - run: stack setup
      - run: stack build --only-dependencies
      - run: stack build

      - save_cache:
          key: v1-stack-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - .stack-work
            - /root/.stack
